# Generated by Django 5.2.6 on 2025-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carshowroom',
            fields=[
                ('plate_number', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=12)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
